<?php

/**
 * @file
 * Module file for ah_dirt.
 */

/**
 * Implements hook_menu().
 */
function ah_dirt_menu() {
  return array(
    'admin/config/services/dirt' => array(
      'title' => 'DiRT Tools Config',
      'description' => 'Configure RESTful DiRT retieval.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('ah_dirt_admin'),
      'file' => 'includes/ah_dirt_admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_services_resources().
 */
function ah_dirt_services_resources() {
  $api = array(
    'item' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves posted items',
          'callback' => '_ah_dirt_item_retrieve',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'fn',
              'type' => 'string',
              'description' => 'Function to perform',
              'source' => array('path' => '0'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'nitems',
              'type' => 'int',
              'description' => 'Number of latest items to get',
              'source' => array('param' => 'nitems'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'since',
              'type' => 'int',
              'description' => 'Posts from the last number of days',
              'source' => array('param' => 'since'),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
      'actions' => array(
        'fetch' => array(
          'help' => 'Retrieves posted items',
          'callback' => '_ah_dirt_item_retrieve',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'fn',
              'type' => 'string',
              'description' => 'Function to perform',
              'source' => array('path' => '0'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'nitems',
              'type' => 'int',
              'description' => 'Number of latest items to get',
              'source' => array('param' => 'nitems'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'since',
              'type' => 'int',
              'description' => 'Posts from the last number of days',
              'source' => array('param' => 'since'),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
  );

  return $api;
}

/**
 * Callback function for item retrieval.
 */
function _ah_dirt_item_retrieve($fn, $nitems, $timestamp) {
  // Sanitize inputs.
  $nitems = intval($nitems);
  $timestamp = intval($timestamp);

  return
      ah_dirt_find_item_items($nitems, $timestamp);
}

/**
 * Gets item posts.
 */
function ah_dirt_find_item_items($nitems, $timestamp) {
  global $language;
  $lang_name = $language->language;
  $nitems = isset($_POST['nitems']) ? $_POST['nitems'] : NULL;
  $serialized_tools = filter_xss($_POST['tools']);
  $tools = unserialize($serialized_tools);
  $query = db_select('node', 'n');
  $query->join('node_revision', 'v', '(n.nid = v.nid) AND (n.vid = v.vid)');
  $query->addField('n', 'nid', 'nid');
  $query->condition('n.type', 'item', '=');
  if ($tools) {
    $query->condition('v.title', $tools, 'in');
  }
  if ($timestamp) {
    $query->condition('v.timestamp', time() - ($timestamp * 60 * 60 * 24), '>');
  }
  $query->orderBy('v.timestamp', 'DESC');
  // Limited by items?
  if ($nitems) {
    $query->range(0, $nitems);
  }
  $items = $query->execute()->fetchAll();
  $objects = array();

  foreach ($items as $item) {
    $alias = drupal_get_path_alias("node/{$item->nid}");
    $node = node_load($item->nid);
    $description = '';
    // Allow for either defined or undefined language type.
    if (isset($node->body['und'][0]['value'])) {
      $description = $node->body[$lang_name][0]['value'];
    }
    if (isset($node->body[$lang_name][0]['value'])) {
      $description = $node->body[$lang_name][0]['value'];
    }
    $object = new stdClass();
    $object->nid = $node->nid;
    $object->title = $node->title;
    $object->description = $description;
    $object->path = $alias;
    $objects[] = $object;
  }
  return $objects;
}

/**
 * Implements hook_block_info().
 */
function ah_dirt_block_info() {

  $blocks['dh_project_block'] = array(
    'info' => t('DHCommons Projects'),
    'status' => FALSE,
    'region' => 'sidebar_first',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/*',
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ah_dirt_block_view($delta = '') {
  module_load_include('inc', 'ah_dirt', 'includes/utilities');
  switch ($delta) {
    case 'dh_project_block':
      $block['subject'] = t('DHCommons');
      $block['content'] = ah_dirt_get_projects();
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function ah_dirt_theme() {
  return array(
    'dirt_dhcommons_item' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/dirt-dhcommons-item',
      'variables' => array('object' => NULL),
    ),
    'dirt_dhcommons_block' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/dirt-dhcommons-block',
      'variables' => array('object' => NULL),
    ),
  );
}
